sonar.projectKey=0ece760d21b905eaf28bb4a6ea329ca506210576
sonar.organization=Iván Estépar
sonar.host.url=https://sonarcloud.io
sonar.sources=app/src
sonar.tests=app/src/test
sonar.exclusions=**/build/**, **/generated/**
sonar.java.binaries=app/build
sonar.kotlin.detekt.reportPaths=app/build/reports/detekt.xml
sonar.android.lint.reportPaths=app/build/reports/lint-results.xml
