sonar.projectKey=ivaanesteepar_FlixFinderTV
sonar.organization=ivaanesteepar
sonar.host.url=https://sonarcloud.io
sonar.sources=app/src
sonar.tests=app/src/test
sonar.exclusions=**/build/**, **/generated/**
sonar.java.binaries=app/build
sonar.kotlin.detekt.reportPaths=app/build/reports/detekt.xml
sonar.android.lint.reportPaths=app/build/reports/lint-results.xml
sonar.coverage.enabled=false


