name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - develop
      - master
  pull_request:
    branches:
      - main
      - develop
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache de Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Forzar permisos de ejecución a gradlew
        run: sudo chmod +x gradlew || true

      - name: Verificar permisos de gradlew
        run: ls -l gradlew

      - name: Compilar proyecto
        run: ./gradlew build

      - name: Generar reporte de cobertura
        run: ./gradlew jacocoTestReport

      - name: Ejecutar SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/test/jacocoTestReport.xml


